### PR TITLE
Naxx40: Construct, Plague, Military, trash adjustments

### PR DESCRIPTION
**Pull request by jellemeeus**
## Fixes
Some shared issues https://github.com/ZhengPeiRu21/mod-individual-progression/issues/70

Bosses
Construct
- [x] Patchwerk
- [x] Grobullus
- [x] Gluth
- [x] Thaddius
- [x] Living Poison aka Frogger before Naxx is missing in lvl 60 instance
- [x] Grobbulus: slime spray damage adjusted
- [x] Grobbulus: debuff explosion damage adjusted
~~-[x] Grobbulus: poison cloud damage, damage reduced by lowering ticktime~~
- [x] Grobbulus: poison cloud damage, use lvl 80 entry what only casts a modified AoE ~3k to ~1.2k
- [x] Gluth: enrage increased, icon not updated (requires custom spell+client patch)
- [x] Thaddius: room Tesla shock reduced damage
- [x] Thaddius: mark damage from 4500 to 2000
- [x] Thaddius: lightning ball (wipe mechanic) adjusted
- [x] Feugen: Power burn 500 every 3 seconds. Missing nature visual shock (requires custom spell). Or do hack with 63705 spell, change yards to 300. -500 mana, -2500 dmg
Military Quarter
- [x] Razuvious: remove throwing knife mechaniac
- [x] Razuvious: reduce damage, range (45yd) of shout. Does not drain mana and ignores LoS. Needs client patch
This is incorrectly fixed in ACore. It uses a spellscript `spell_four_horsemen_consumption` to hardcode 4250 if not 10man normal. Should do proper scaling but 25man damage matches Naxx40. so skip for now
Plague Quarter
- [x] Noth: curse range adjusted, number of curses, faster curses
- [x] Noth: curse damage reduced, range increased
- [x] Heigan: fever dot 3k -> 500
- [x] Heigan: Poison Cloud, (AoE when he teleports), damage reduced to 500
- [x] Heigan: Reduce damage from eruption
- [x] Loatheb: Deathbloom damage reduced to 33dps for 6 sec instead of 200dps
- [x] Loatheb: Spores +50% to +60% caster crit

Trash
Plague Quarter
- [x] Infectious Ghoul: damage unchanged, updated rend, update frenzy
- [x] Plague Slime: unchanged
- [x] Mutaged Grub, reduce aoe dmg ~400 -> ~200
- [x] Frenzied Bat, update frenzy id
- [x] Plagued Bat, update IC timings
- [x] Plague Beast, smartAI trample
- [x] Eye Stalk, smartAI reduce damage, movement speed reduction is less
- [x] Eye Stalk, smartAI missing OOC rp and birth animation

Military Quarter
- [x] Horse mounts from trash before Razuvious are lvl 80
- [x] Death Knight Captain, updated smartAI to cast whirlwind/stun
- [x] Plagued Gargoyle, smartAI
- [x] Unholy swords, looks the same
- [x] Unholy Axe, looks the same
- [x] Death Lord, add smartAI
- [x] Deathknight, update smartAI
- [x] Skeletal Smith, update SmartAI
- [x] Bony Construct, update smartAI
- [x] Spirit of Naxxramas, update smartAI reduce shadow bolt damage from 2.2k to 1.8k
- [x] Skeletal Steed, smartAI add trample and intercept

Construct Quarter
- [x] Sewage Slime, slime that spawns from Grobulus are lvl 80
- [x] Pathwerk Trash (see below): awkward pathing with formations?
- [x] Bile Retcher 351022  - 27807 Bile Vomit - ~5k instant, ~1200 dot to ~1500 instant, 250 dot
- [x] Patchwork Golem - cleave based on weapon damage instead of raw damage in classic. Requires custom patch
- [x] Embalming Slime - same AoE damage, unchanged
- [x] Mad Scientist - Heal, reduced from ~20% hp to ~10% hp. Vanilla is raw ~3k
- [x] Mad Scientist - Mana Burn ~3.5k to ~1.5k
- [x] Surgical Assitant - Mind Flay damage from 1.5k to 600 per tick
- [x] Living Monstrosity - Chain Lightning damage from ~4k to ~1k. (Chain Lightning should 3 to 10. Range 45 to 30, requires custom script)
- [x] Living Monstrosity - Summon lvl 62 Lightning Totem
- [x] Lightning Totem - lvl62 - Shock damage ~3k to ~2k
- [x] Stitched Spewer - unchanged, weapon damage instead of raw 2k dmg
- [x] Toxic Tunnel - unchanged, damage should be 300->200. Triggered spell 28369. Requires custom patch
- [x] Necropolis Acolyte - add smartAI, Casts Shadow Bolt Volley and Arcane Explosion
- [x] Plagued Ghoul - 351078, add smartAI
- [x] Deathknight Vindicator, add smartAI
- [x] Razuvious, removed knife throw mechanic, disrupting shout adjusted to 45yd and less damage. No power burn without client patch or remove animation

- [x] Issue Bony Construct patrol/creature_formation guid 3612410
VMangos/CMangos show 5 points. No waypoints. 3 mobs wander with 15yd, 2 path
https://youtu.be/4UTQFrMRk5c?si=ye3fIhp7pg88f03C&t=5222 classic shows 4+2 pathing
ACore 25 shows 4+2 pathing

- [x] Issue Patchwerk Trash:
Creature formations of patchwork golems. Awkward pathing
Removed wandering from non-leader, but does not look correct
(361229, 361227, 10.8064, 306.6246666000065, 515, 0, 0),
(361229, 361228, 7.08383, 261.72081828001365, 515, 0, 0),
(361229, 361246, 6.33888, 349.3644533277902, 515, 0, 0),

## GM commands to help test

attunement - reputation honored - complete quest
```
.mod reputation 529 10000
.quest complete 9121
.go creature 54192
```

teleport to naxx entrance inside strat
```
.go xyz 3960 -3392 121 329
```

reset instance
```
.instance unbind all
```

10man HC
```
/script SetRaidDifficulty(4)
```

go Thaddius
```
.go c 130957
```

4H door
```
.gobject activate 65753
.go c 130961
```

patchwerk
```
.go c 128135
```

# Tools used 
Look in CPP or smartAI with Keira3 https://github.com/azerothcore/Keira3

https://github.com/stoneharry/WoW-Spell-Editor

2 WoW-Spell-Editors side by side to compare 335 and 112

## SmartAI CMangos 1.12
cmangos db,
cmangos core,

https://github.com/BAndysc/WoWDatabaseEditor

Database Editor smartAI -> write smartAI with Keira

## Exploring DBC Spells.

https://github.com/azerothcore/SpellWork

# What's left todo, not in this PR

- [ ] (skip) Grobbulus: poison cloud damage reduce damage properly. (requires custom spell+client patch)
- [ ] (waiting upstream) Gothik, waiting for upstream changes
- [ ] (waiting upstream) Blaumeux: Void Zone casts Consumption (28865). Should do 4k damage, radius 2 -> 3
- [ ] Blaumeux+Zeliek: move
- [ ] Horsemen: no pathing on pull
- [ ] Blaumeux+Zeliek: Remove Punish spells for not being in range
- [ ] Heigan: Adjust Eruption calc so it no longer uses SetHitDamage(damage) which ignores defensive CDs?
- [ ] Infectious Ghoul: missing low hp text
- [ ] (skip, do below instead) Eye Stalk, 36y-90y evade smartAI. Stuck in combat, not evading
- [ ] Heigan: Eye Stalk/Heigan room adds should all despawn after defeating Heigan
https://github.com/cmangos/mangos-wotlk/blob/a3a647a0da14f9b6de483f99149e09b6ff6e7c8a/src/game/AI/ScriptDevAI/scripts/northrend/naxxramas/naxxramas.cpp#L419
- [ ] Necro Knight, has smartAI (see Necro Knight Guardian)
- [ ] Necro Knight Guardian, smartAI, similar implementation to Necro Knight might be better?
- [ ] Unholy Staff Arcane Explosion, damage is similar (~2k) but range is 45yd instead of 20yd. Requires spellscript to reduce radius
- [ ] Doom Touched Warrior, missing smartAI, casts dazed?
- [ ] Dark Touched Warrior, smartAI casts whirlwind, should only cast dazed?
- [ ] Death Touched Warrior, missing smartAI, should drop threat?
- [ ] Risen Deathknight, missing smartAI, casts dazed?
- [ ] Sewage Slime, disease cloud 28153. Ticks for 600 instead of 300. Trigger spell requires spellscript HandleDamage
- [ ] Plagued Ghoul - missing smartAI say texts
- [ ] Razuvious DK Understudy. has 2, needs 4

Client side patch:
- [ ] 4H, needs client patch for mograine mark
- [ ] Heigan: disruption should be power burn, 29310, client side patch needed
- [ ] Loatheb: Deathbloom -> Poison Aura. needs custom patch
- [ ] Loatheb: Deathbloom needs to do 200 dps after 6 seconds, patch needed

### CODE REVIEW

**Comment by ZhengPeiRu21** [comment]
Thank you for your continued fixes! Please let me know when your work here is done and I will test then merge.

**Comment by jellemeeus** [comment]
> Thank you for your continued fixes! Please let me know when your work here is done and I will test then merge.

I'm working my way through the naxx instance and updating https://github.com/jellemeeus/mod-progression-system-naxx25-60/tree/naxx 

I'll share changes soon since it's similar files

**Comment by jellemeeus** [comment]
I went through Naxx (Plague, Military, Plague Quarter) and aimed to reduce the damage of the wrath spells. I did fixes to pathing of Patchwork/Bony Constructs plus some others that I encountered. There should be minimal amount of custom spells, just for a summoning. Feugen casts an AoE mana burn, the visual is missing. Some others like Razuvious likely need a client patch to do the Disrupting Shout mechanic properly. 

I don't know how you want to go about reviewing this? it's a bit much too untangle for seperate PRs

**Comment by ZhengPeiRu21** [comment]
Thanks again for your work. Having it in a single PR is fine. As much as possible, I'd like to avoid the requirement for a client patch, even if that means we're not able to reach 100% accuracy. I'd prefer to get as accurate as possible within the constraints of the WotLK client, even if it means having to make some small compromises (for example, in the Four Horsemen, the Mark of Mograine spell was replaced with the Mark of Rivendare, so it currently has the wrong name and visual.) Please let me know if you feel otherwise; I'm open to options.

**Comment by jellemeeus** [comment]
A first priority is to get the scaling/spells down to vanilla levels to make the raid more playable. I try to avoid a client side patch as well as it brings extra challenges. It's also a hassle to work with and from what I've seen, it can be done without just fine. As I went through I noted where a patch would be useful or even required to achieve the accurate feel of naxx40. To me, it is future work but it's important to note spells/mechanics to do any potential polishing later. As of now I don't feel it to be necessary

**Comment by jellemeeus** [comment]
I updated the comment to show what fixes are included in this PR

**Comment by ZhengPeiRu21** [comment]
Thank you once again for all of these fixes!

**Pull request merged**
